### ISSUE TITLE
Consider porting to Win 10 Mobile using Project Astoria / Bridge

### ISSUE THREAD

**Issue by episource** [felixb/websms#12]
With smsdroid and especially websms you made two excellent apps. At first, thanks a lot for giving us these great apps!

It would be awesome if **websms** and maybe also smsdroid would be available for windows phone, too. Using [Microsoft's Project Astoria / Bridge](https://dev.windows.com/en-us/bridges/android), this might be feasible without too much effort. I would like to support porting websms by buying you a [Lumia 635 (1GB RAM)](http://www.amazon.de/Nokia-Smartphone-Megapixel-Snapdragon-Prozessor/dp/B00S8LF89Q/ref=sr_1_2?ie=UTF8&qid=1444407125&sr=8-2&keywords=lumia+635) compatible with current Win 10 Mobile Insider preview and most probably also the final Win 10 Mobile build...

**Comment by felixb** [comment]
Thanks for the offer. I currently lack the spare time for porting the app.
It is an open source project though. Feel free do do it yourself or ask anybody else to do so.
