### ISSUE TITLE
Allow WebSMS to be the Androids Default SMS App

### ISSUE THREAD

**Issue by profundus-it** [felixb/websms#14]
Hi Felix

Thanks a lot for your web sms app.
Using the sunrise connector I'm able to save some money because their 50 free sms/month. Wow.

But one feature would be great, eather: WebSMS App can't be set as Androids default sms app.
Reason is that I'm using other SMS-sending Apps (Blaupunkt Alarm System etc.), and these guys are using the default App. So it's really a waste of money, because Sunrise as my provider will charge me for this.

Thanks again
Regards
Steffen

**Comment by felixb** [comment]
There is nothing I can do. 
These apps are using the android system to send the messages. 

The developers of these apps could use WebSMS, though. They need to implement the same intent based interface SMSdroid is using. 
Feel free to point them to this project in case they want to integrate.
