### ISSUE TITLE
Fishtext connector does not work 

### ISSUE THREAD

**Issue by lorr1e1** [felixb/websms#18]
Have reported this several times developer has not replied. 

help

**Comment by felixb** [comment]
This github project is about the websms app only. I'm the author of that app and a few connectors. Other connectors are developed by other people.

I'm sorry, but I can't do anything. I think, the author "Fintan Fairmichael" of the connector abandoned the project some time ago.

This is the github project of the fishtext connector: https://github.com/fintanf/websms-connector-fishtext
This is the play store site of the fishtext connector: https://play.google.com/store/apps/details?id=com.fairmichael.fintan.websms.connector.fishtext&hl=en

**Comment by Vayira** [comment]
unfortunately your project is only as good as the connectors so i suppose a lot of people will stop using it despite many years satisfaction.
