### ISSUE TITLE
WebSMS doesn't store sent messages on Android 5

### ISSUE THREAD

**Issue by websmsuser** [felixb/websms#19]
Hi Felix,

WebSMS doesn't store sent messages on Android 5, I've even tried to use SMSdroid but they don't show up. Maybe this is a change of system api?

I've no idea about android development but I could test some things.

Yours,
H

Android-Version: 5.0.2
Model: Moto G (2015, 2nd Generation)
System: 22.32.28.titan_retaildsds.retaildsdsall.en.03 retde
Build-Number: LXB22.46-28

**Comment by felixb** [comment]
this is a known problem since android 4.4. the system restricts write access to the message database to one single app. the only workaround is, to use smsdroid as your default messaging app. websms communicates with smsdroid to save sent messages.
